### ISSUE TITLE
Problem with Blockquotes

### ISSUE THREAD

**Issue by Bluemoondragon07** [zalenza/Abecedarium-theme#2]
In reading mode, blockquotes will have large grey text floating to the side that says, "quotes-left".

![Screenshot 2023-01-03 150109](https://user-images.githubusercontent.com/121056178/210440802-adda8759-1f49-48d4-8a84-356ad54d0400.png)

It's really faint text, so it's not *that* noticeable. Just a little something I noticed. But I really love your theme! Keep up the great work.

**Comment by zalenza** [comment]
Thanks for the notice (and the kind words). The icon is from the [IcoMoon](https://icomoon.io/#icons-icomoon) font (free version). I'm trying to figure out how to embed either the SVG or the font itself.

**Comment by zalenza** [comment]
I've removed this icon for now.
