### ISSUE TITLE
Folders Icons in Navigation Panel Do Not Appear Correctly

### ISSUE THREAD

**Issue by andywhitaker** [zalenza/Abecedarium-theme#3]
The folder arrows are not placed correctly and are overlapping the folder names after the most recent updates:
![image](https://github.com/zalenza/Abecedarium-theme/assets/32944047/9909e1f4-1902-4c73-bf25-6f287a6c998d)

This is seen in "Light Mode" and "Dark Mode"

**Comment by chr-rich309** [comment]
I do have that issue as well. Which is unfortunate because it's by far my favorite theme.

**Comment by zalenza** [comment]
This should be fixed in the latest update.

**Comment by andywhitaker** [comment]
Looks good and thank you!!!
